#!/bin/bash
 echo "school" 
 !#/bin/bash
 echo "schol" 
- e  #!/bin/bash\n echo " school" 
 #!/bin/bash/
 echo "school" 
 #!/bin/bash
echo "school" 
 #!/bin/bash
echo " school " 
 #!/bin/bash
echo " ALX  " 
#!/bin/bash
echo " school  " 
